### ISSUE TITLE
Peer Review by chnewell

### ISSUE THREAD

**Issue by Pyranem6** [math241s24/project-02-omar#1]
---
name: Proposal peer review
about: Peer review of final project proposal
title: Proposal peer review
labels: ''
assignees: ''
---

The following is the peer review of the project proposal by chnewell. The team members that participated in this review are 

- Christopher Newell @Pyranem6

- Describe the goal of the project.
"The goal is to create some interesting and interactive visualizations for analysis of international air travel in the United States."

- Describe the data used or collected.
The data source used is the U.S. Department of Transportation made by Randall Keizer.

- Describe how the research question will be answered, e.g. what approaches / methods will be used.
Data analysis will be done to find interesting trends in the data. I wasn't able to find anything concrete as to how this will be done specifically, or what packages will be used. It might be a good idea to figure that out as soon as possible.

- Is there anything that is unclear from the proposal?
It is unclear what the visualizations will consist of. Will there be visualizations about the number of flights per month over the years? Will there be a geographic component, to visualize the departure and arrival points of flights? Is there going to be any regression analysis to predict flight numbers based on certain variables (not exactly visual, but would be pretty cool)?

I assume that there is something planned; getting what that is on paper (metaphorically) is a good next step for the project.

- Provide constructive feedback on how the team might be able to improve their project.
Looking at the variables that are in the data set, it is somewhat unclear what the contexts are. For example, I know what an airline id is, but I would have no idea how to use that data in any meaningful way. I would recommend adding into the presentation a part in which you explain the variables you chose versus the variables you didn't, and why you chose to investigate those variables in specific.

Obviously, it would be really cool if an additional data set could be used to add context to some of the trends. For example, getting the GDP of each country and comparing that to the number of flights between that country and the U.S. might show either a clear correlation or some strange behaviors. However, this is beyond the scope of the project you are currently doing, so don't take this as a necessity.

- What aspect of this project are you most interested in and would like to see highlighted in the presentation.
I'm interested to see the countries that have the greatest change in flights from or to the U.S. over time. For example, what countries had a ton of flights in the past and relatively few now, or vice versa?

- Provide constructive feedback on any issues with file and/or code organization.
I didn't see anything that needed fixing as far as this.

- (Optional) Any further comments or feedback?
Cool project! I'm excited to see what you'll do. Looks good so far.

**Comment by omaryoussif** [comment]
All these points have been addressed, thank you for the feedback!
